name: Access Secret Key Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Access Secret Key
      run: echo "AUTHTOK=$AUTHTOK" >> $GITHUB_ENV
      env:
        AUTHTOK: ${{ secrets.AUTHTOK }}
        AUTH_HOST: ${{ secrets.AUTH_HOST }}
        AUTH_TO: ${{ secrets.AUTH_TO }}
        AUTH_UN: ${{ secrets.AUTH_UN }}
    - name: Run JavaScript file
      run: node cont.js
